version: '3.7'
services:

  adopet-backend-api:
    image: lucasfugisawa/adopet-backend-api
    depends_on:
      - local-mysql-database
    ports:
      - '8888:8888'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8888/starter-test/actuator/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 5s

  local-mysql-database:
    image: mysql/mysql-server:8
    container_name: local-mysql-database
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: adopet
      MYSQL_DATABASE: adopet-password
